version: 2
jobs:
  build:
    docker:
      - image: daewok/sbcl:1.5.2-alpine3.9
    
    working_directory: ~/quicklisp/local-projects/circleci-101

    steps:
      - checkout

      - run:
          name: Install wget
          command: |
            apk update
            apk add wget

      - run:
          name: Install quicklisp
          command: |
            wget https://beta.quicklisp.org/quicklisp.lisp
            cat quicklisp.lisp init-quicklisp.lisp | sbcl
            cp .sbclrc ~/
            mkdir -p /root/.config/common-lisp
            cp asdf-output-translations.conf /root/.config/common-lisp

      - restore_cache:
          keys:
            - deps-{{ checksum "circleci-101.asd" }}-{{ checksum "circleci-101-test.asd" }}
            - deps-

      - run:
          name: Build
          command: cat build.lisp | sbcl

      - run:
          name: Test
          command: cat test.lisp | sbcl

      - save_cache:
          key: deps-{{ checksum "circleci-101.asd" }}-{{ checksum "circleci-101-test.asd" }}
          paths:
            - ~/.cache/common-lisp

workflows:
  version: 2
  default:
    jobs:
      - build